version: '3.2'

services:

  ffmpeg:
    image: jrottenberg/ffmpeg

  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - type : bind
        source : "N:/" #local host path eg N: mapped to NAS
        target : /media
    depends_on:
      - ffmpeg
