version: '3.2'
services:
  ffmpeg:
    image: jrottenberg/ffmpeg
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - ffmpeg
    volumes:
      - type : bind
        source : "N:/" #local host path eg N: mapped to NAS
        target : /media